from __future__ import annotations

from collections import defaultdict
from datetime import datetime
from math import exp, log

from widegold.domain.enums import DataStatus, EventVerificationStatus, SourceTier
from widegold.engine.factor_state import event_impact_0_100
from widegold.schemas.events import StructuredEvent
from widegold.schemas.factors import FactorState, FactorStateComponents
from widegold.schemas.resilience import FactorInput, FactorResolutionSummary
from widegold.settings.config import (
    asset_config,
    factor_config,
    factor_runtime_config,
    resilience_config,
)


def _clip(value: float, lo: float = -100.0, hi: float = 100.0) -> float:
    return max(lo, min(hi, value))


def _hours_between(later: datetime, earlier: datetime) -> float:
    return max(0.0, (later - earlier).total_seconds() / 3600.0)


def _runtime_meta(factor_id: str) -> dict:
    runtime = factor_runtime_config()
    merged = dict(runtime.get("defaults", {}))
    merged.update(runtime.get("overrides", {}).get(factor_id, {}))
    if merged.get("max_stale_hours") is None:
        freq = merged.get("update_frequency", "daily")
        merged["max_stale_hours"] = resilience_config()["factor_resolution"][
            "default_max_stale_hours"
        ].get(freq, 72)
    return merged


def _stale_reliability(
    base_reliability: float, age_hours: float, max_stale_hours: float
) -> float:
    cfg = resilience_config()["factor_resolution"]
    floor = float(cfg["stale_reliability_floor"])
    half_life = max(1.0, max_stale_hours * float(cfg["stale_half_life_ratio"]))
    decay = exp(-log(2) * age_hours / half_life)
    return max(floor, base_reliability * decay)


def _state_key(factor_id: str, asset_id: str | None) -> str:
    return f"{factor_id}::{asset_id}" if asset_id else factor_id


def _factor_targets(meta: dict) -> list[str | None]:
    if meta.get("scope", "global") != "asset":
        return [None]
    family = meta.get("family")
    return [
        item["id"]
        for item in asset_config().get("assets", [])
        if item.get("family") == family and item.get("active", True)
    ]


def _event_adjustments(
    events: list[StructuredEvent],
    factor_defs: dict[str, dict],
    as_of: datetime,
) -> tuple[dict[tuple[str, str | None], float], dict[tuple[str, str | None], list]]:
    adjustment: dict[tuple[str, str | None], float] = defaultdict(float)
    ids: dict[tuple[str, str | None], list] = defaultdict(list)

    for event in events:
        if event.verification_status in {
            EventVerificationStatus.UNVERIFIED,
            EventVerificationStatus.REJECTED,
        }:
            continue
        if event.source_tier == SourceTier.D:
            continue
        verification_multiplier = (
            1.0
            if event.verification_status == EventVerificationStatus.VERIFIED
            else 0.60
        )
        event_time = event.effective_at or event.published_at
        age_days = max(0.0, (as_of - event_time).total_seconds() / 86400.0)
        impact = event_impact_0_100(event, age_days=age_days) * verification_multiplier

        for mapping in event.factors:
            meta = factor_defs.get(mapping.factor_id)
            if meta is None:
                continue
            for asset_id in _factor_targets(meta):
                # asset_overrides is a relative relevance multiplier generated by the event
                # intelligence layer. It may amplify or mute a scoped event but does not replace
                # the deterministic factor/asset sensitivity matrix.
                multiplier = (
                    float(event.asset_overrides.get(asset_id, 1.0))
                    if asset_id is not None
                    else 1.0
                )
                key = (mapping.factor_id, asset_id)
                adjustment[key] += (
                    mapping.direction
                    * impact
                    * mapping.mapping_confidence
                    * multiplier
                )
                ids[key].append(event.event_id)
    return adjustment, ids


def resolve_factor_states(
    inputs: list[FactorInput],
    events: list[StructuredEvent],
    as_of: datetime,
    previous_states: dict[str, FactorState] | None = None,
    *,
    event_source_available: bool = True,
) -> tuple[list[FactorState], FactorResolutionSummary]:
    """Resolve the 27 logical factors into global and asset-scoped physical states.

    Resolution is intentionally partial-data tolerant:
      current VALID/PARTIAL/STALE input -> last-known-good -> event-only -> unavailable.

    ``event_source_available`` distinguishes a successful news scan with no relevant event from a
    failed/incomplete event source. Only the former may legitimately produce an event-neutral
    state for ``neutral_if_absent`` factors such as policy/Fed surprise.
    """

    previous_states = previous_states or {}
    input_map: dict[tuple[str, str | None], FactorInput] = {}
    for item in inputs:
        key = (item.factor_id, item.asset_id)
        current = input_map.get(key)
        # If duplicated upstream inputs leak through, keep the most recently observed row rather
        # than making ordering decide the production result.
        if current is None or (item.observed_at or as_of) >= (current.observed_at or as_of):
            input_map[key] = item

    factor_defs = {item["id"]: item for item in factor_config().get("factors", [])}
    event_adjustment, event_ids = _event_adjustments(events, factor_defs, as_of)
    logic_version = str(factor_runtime_config().get("version", "1.0.0"))

    resolved: list[FactorState] = []
    counters = {status: 0 for status in DataStatus}
    warnings: list[str] = []
    resolution_cfg = resilience_config()["factor_resolution"]
    allow_lkg = bool(resolution_cfg["allow_last_known_good"])

    for factor_id, meta in factor_defs.items():
        runtime = _runtime_meta(factor_id)
        max_stale = max(1.0, float(runtime["max_stale_hours"]))
        base_reliability = float(meta.get("reliability", 0.7))

        for asset_id in _factor_targets(meta):
            key = (factor_id, asset_id)
            label = _state_key(factor_id, asset_id)
            current = input_map.get(key)
            event_component = _clip(event_adjustment.get(key, 0.0))
            related_event_ids = event_ids.get(key, [])
            state: FactorState | None = None

            if current and current.value is not None and current.status in {
                DataStatus.VALID,
                DataStatus.PARTIAL,
                DataStatus.STALE,
            }:
                observed = current.observed_at or as_of
                age_hours = _hours_between(as_of, observed)
                effective_status = current.status
                if effective_status == DataStatus.VALID and age_hours > max_stale:
                    effective_status = DataStatus.STALE

                if effective_status != DataStatus.STALE or age_hours <= max_stale:
                    blended = _clip(0.80 * current.value + 0.20 * event_component)
                    reliability = min(
                        base_reliability,
                        current.reliability if current.reliability > 0 else base_reliability,
                    )
                    if effective_status == DataStatus.STALE:
                        reliability = _stale_reliability(
                            reliability, age_hours, max_stale
                        )
                        coverage = max(0.25, 1.0 - age_hours / max_stale)
                    elif effective_status == DataStatus.PARTIAL:
                        coverage = 0.70
                    else:
                        coverage = 1.0
                    state = FactorState(
                        factor_id=factor_id,
                        asset_id=asset_id,
                        as_of_ts=as_of,
                        state=blended,
                        components=FactorStateComponents(
                            level=current.value, event=event_component
                        ),
                        reliability=reliability,
                        coverage=coverage,
                        status=effective_status,
                        evidence_refs=current.source_ids,
                        quality_flags=list(current.warnings),
                        event_ids=related_event_ids,
                        logic_version=logic_version,
                        data_vintage=observed.isoformat(),
                    )
                    if effective_status == DataStatus.STALE:
                        warnings.append(
                            f"{label}: current input is stale ({age_hours:.1f}h old)"
                        )

            if state is None:
                previous = previous_states.get(label)
                if previous is None and asset_id is None:
                    previous = previous_states.get(factor_id)
                age_hours = (
                    _hours_between(as_of, previous.as_of_ts)
                    if previous is not None and allow_lkg
                    else max_stale + 1
                )

                if previous is not None and allow_lkg and age_hours <= max_stale:
                    previous_rel = previous.reliability or base_reliability
                    reliability = _stale_reliability(
                        min(base_reliability, previous_rel), age_hours, max_stale
                    )
                    blended = _clip(0.90 * previous.state + 0.10 * event_component)
                    coverage = max(0.25, 1.0 - age_hours / max_stale)
                    state = FactorState(
                        factor_id=factor_id,
                        asset_id=asset_id,
                        as_of_ts=as_of,
                        state=blended,
                        components=FactorStateComponents(
                            level=previous.state, event=event_component
                        ),
                        reliability=reliability,
                        coverage=coverage,
                        status=DataStatus.STALE,
                        evidence_refs=previous.evidence_refs,
                        quality_flags=[*previous.quality_flags, "last_known_good"],
                        event_ids=related_event_ids,
                        logic_version=logic_version,
                        data_vintage=previous.data_vintage,
                    )
                    warnings.append(
                        f"{label}: using last-known-good state ({age_hours:.1f}h old)"
                    )
                elif (
                    runtime.get("neutral_if_absent")
                    and event_source_available
                    and abs(event_component) < 1e-9
                ):
                    state = FactorState(
                        factor_id=factor_id,
                        asset_id=asset_id,
                        as_of_ts=as_of,
                        state=0.0,
                        components=FactorStateComponents(level=0.0, event=0.0),
                        reliability=base_reliability,
                        coverage=1.0,
                        status=DataStatus.VALID,
                        evidence_refs=[],
                        quality_flags=[],
                        event_ids=[],
                        logic_version=logic_version,
                        data_vintage="event-neutral",
                    )
                elif abs(event_component) > 1e-9:
                    state = FactorState(
                        factor_id=factor_id,
                        asset_id=asset_id,
                        as_of_ts=as_of,
                        state=_clip(event_component),
                        components=FactorStateComponents(event=event_component),
                        reliability=max(0.35, base_reliability * 0.75),
                        coverage=0.55,
                        status=DataStatus.PARTIAL,
                        evidence_refs=[],
                        quality_flags=["event_only_partial"],
                        event_ids=related_event_ids,
                        logic_version=logic_version,
                        data_vintage="event-only",
                    )
                    warnings.append(
                        f"{label}: no fresh base data; event-only partial state used"
                    )
                else:
                    reason = (
                        "event source unavailable"
                        if runtime.get("neutral_if_absent") and not event_source_available
                        else "unavailable"
                    )
                    state = FactorState(
                        factor_id=factor_id,
                        asset_id=asset_id,
                        as_of_ts=as_of,
                        state=0.0,
                        components=FactorStateComponents(),
                        reliability=0.0,
                        coverage=0.0,
                        status=DataStatus.UNAVAILABLE,
                        evidence_refs=[],
                        quality_flags=[reason.replace(" ", "_")],
                        event_ids=[],
                        logic_version=logic_version,
                        data_vintage=None,
                    )
                    warnings.append(f"{label}: {reason}")

            counters[state.status] += 1
            resolved.append(state)

    return resolved, FactorResolutionSummary(
        total_factors=len(factor_defs),
        state_rows=len(resolved),
        valid=counters[DataStatus.VALID],
        stale=counters[DataStatus.STALE],
        partial=counters[DataStatus.PARTIAL],
        unavailable=counters[DataStatus.UNAVAILABLE],
        conflicted=counters[DataStatus.CONFLICTED],
        warnings=warnings,
    )
